### ISSUE TITLE
Explicit pip installation

### ISSUE THREAD

**Issue by tokejepsen** [tokejepsen/conda-git-deployment#17]
**Goal**

Make the installation of git repositories explicit with commands in the environment file.

**Motivation**

Currently the automated process of installing the git repositories cannot be modified. In the case of wanting to install a git repository locally you have to install with conda's environment pip syntax. This means you have to download the repository every time you want to update the environment, which for large repositories takes time.

**Implementation**

You can currently install a git repository with the subcommands via. ```pip``` or ```setup.py```. The problem is that subcommands are run on every startup, where we would only want to run the install commands on install and updating.
The solution could be to tag/mark subcommands for installation/updating and launching.

Possible syntax:

```yaml
name: conda-git-example
dependencies:
- python=2.7
- git:
  - https://github.com/tokejepsen/conda-git-example.git:
    - on_update:
        - pip install git+file:$REPO_PATH
    - python $REPO_PATH/environment.py
```
This syntax would ensure backward compatibility.

**Comment by tokejepsen** [comment]
Installing large repositories to the local environment can currently be achieved by manually installing the repository with a subcommand:

```yaml
dependencies:
- python=2.7
- git:
  - https://github.com/pyqt/python-qt5.git:
    - python $REPO_PATH/setup.py install
name: test-environment
```

This will install the repository twice, once with conda-git-deployment and once with the subcommand.
